// Endpoint
export const urlRoot = 'http://localhost:3000/'


// Orders constants
export const COLLECTION_ORDERS_FIELD_ID = 'id'
export const COLLECTION_ORDERS_FIELD_TITLE = 'title'
export const COLLECTION_ORDERS_FIELD_DETAILS = 'details'
export const COLLECTION_ORDERS_FIELD_CUSTOMERS = 'customers'
export const COLLECTION_ORDERS_FIELD_PRODUCTS_ORDERED = 'productsOrdered'
export const COLLECTION_ORDERS_FIELD_CREATED_AT = 'createdAt'
export const COLLECTION_ORDERS_FIELD_MODIFIED_AT = 'modifiedAt'
export const COLLECTION_ORDERS_FIELD_IS_DELETED = 'isDeleted'

export const COLLECTION_TESTING = 'Testing'

// ======= HTTP return codes ==========

// INFORMATIVE RESPONSES
export const HTTP_ANSWER_CODES_100_CONTINUE = 100
export const HTTP_ANSWER_CODES_101_SWITCHING_PROTOCOL = 101
export const HTTP_ANSWER_CODES_102_PROCESSING = 102
export const HTTP_ANSWER_CODES_103_EARLY_HINTS = 103

// SUCCESSFUL RESPONSES
export const HTTP_ANSWER_CODES_200_OK = 200
export const HTTP_ANSWER_CODES_201_CREATED = 201
export const HTTP_ANSWER_CODES_202_ACCEPTED = 202
export const HTTP_ANSWER_CODES_203_NON_AUTHORITATIVE_INFORMATION = 203
export const HTTP_ANSWER_CODES_204_NO_CONTENT = 204
export const HTTP_ANSWER_CODES_205_RESET_CONTENT = 205
export const HTTP_ANSWER_CODES_206_PARTIAL_CONTENT = 206
export const HTTP_ANSWER_CODES_207_MULTI_STATUS = 207
export const HTTP_ANSWER_CODES_208_ALREADY_REPORTED = 208
export const HTTP_ANSWER_CODES_226_IM_USED = 226

// REDIRECTION RESPONSES
export const HTTP_ANSWER_CODES_300_MULTIPLE_CHOICE = 300
export const HTTP_ANSWER_CODES_301_MOVED_PERMANENTLY = 301
export const HTTP_ANSWER_CODES_302_FOUND = 302
export const HTTP_ANSWER_CODES_303_SEE_OTHER = 303
export const HTTP_ANSWER_CODES_304_NOT_MODIFIED = 304
export const HTTP_ANSWER_CODES_305_USE_PROXY = 305
export const HTTP_ANSWER_CODES_306_UNUSED = 306
export const HTTP_ANSWER_CODES_307_TEMPORARY_REDIRECT = 307
export const HTTP_ANSWER_CODES_308_PERMANENT_REDIRECT = 308

// CLIENT RESPONSES
export const HTTP_ANSWER_CODES_400_BAD_REQUEST = 400
export const HTTP_ANSWER_CODES_401_UNAUTHORIZED = 401
export const HTTP_ANSWER_CODES_402_PAYMENT_REQUIRED = 402
export const HTTP_ANSWER_CODES_403_FORBIDDEN = 403
export const HTTP_ANSWER_CODES_404_NOT_FOUND = 404
export const HTTP_ANSWER_CODES_405_METHOD_NOT_ALLOWED = 405
export const HTTP_ANSWER_CODES_406_NOT_ACCEPTABLE = 406
export const HTTP_ANSWER_CODES_407_PROXY_AUTHENTICATION_REQUIRED = 407
export const HTTP_ANSWER_CODES_408_REQUEST_TIMEOUT = 408
export const HTTP_ANSWER_CODES_409_CONFLICT = 409
export const HTTP_ANSWER_CODES_410_GONE = 410
export const HTTP_ANSWER_CODES_411_LENGTH_REQUIRED = 411
export const HTTP_ANSWER_CODES_412_PRECONDITION_FAILED = 412
export const HTTP_ANSWER_CODES_413_PAYLOAD_TOO_LARGE = 413
export const HTTP_ANSWER_CODES_414_URI_TOO_LONG = 414
export const HTTP_ANSWER_CODES_415_UNSUPORTED_MEDIA_TYPE = 415
export const HTTP_ANSWER_CODES_416_RANGE_NOT_SATISFIABLE = 416
export const HTTP_ANSWER_CODES_417_EXPECTATION_FAILED = 417
export const HTTP_ANSWER_CODES_418_IM_A_TEAPOT = 418
export const HTTP_ANSWER_CODES_421_MISDIRECTED_REQUEST = 421
export const HTTP_ANSWER_CODES_422_UNPROCESSABLE_ENTITY = 422
export const HTTP_ANSWER_CODES_423_LOCKED = 423
export const HTTP_ANSWER_CODES_424_FAILED_DEPENDENCY = 424
export const HTTP_ANSWER_CODES_425_TOO_EARLY = 425
export const HTTP_ANSWER_CODES_426_UPGRADE_REQUIRED = 426
export const HTTP_ANSWER_CODES_428_PRECONDITION_REQUIRED = 428
export const HTTP_ANSWER_CODES_429_TOO_MANY_REQUESTS = 429
export const HTTP_ANSWER_CODES_431_REQUEST_HEADER_FIELDS_TOO_LARGE = 431
export const HTTP_ANSWER_CODES_415_UNAVAILABLE_FOR_LEGAL_REASONS = 451

// SERVER ERROR RESPONSES
export const HTTP_ANSWER_CODES_500_INTERNAL_SERVER_ERROR = 500
export const HTTP_ANSWER_CODES_501_NOT_IMPLEMENTED = 501
export const HTTP_ANSWER_CODES_502_BAD_GATEWAY = 502
export const HTTP_ANSWER_CODES_503_SERVICE_UNAVAILABLE = 503
export const HTTP_ANSWER_CODES_504_GATEWAY_TIMEOUT = 504
export const HTTP_ANSWER_CODES_505_HTTP_VERSION_NOT_SUPPORTED = 505
export const HTTP_ANSWER_CODES_506_VARIANT_ALSO_NEGOTIATES = 506
export const HTTP_ANSWER_CODES_507_INSUFFICIENT_STORAGE = 507
export const HTTP_ANSWER_CODES_508_LOOP_DETECTED = 508
export const HTTP_ANSWER_CODES_510_NOT_EXTENDED = 510
export const HTTP_ANSWER_CODES_511_NETWORK_AUTHENTICATION_REQUIRED = 511

