// Endpoint
export const urlRoot = 'http://localhost:3000/'


// Orders constants
exports.COLLECTION_ORDERS_FIELD_TABLE_NAME = 'tableName'
exports.COLLECTION_ORDERS_FIELD_DETAILS = 'details'
exports.COLLECTION_ORDERS_FIELD_CUSTOMERS = 'customers'
exports.COLLECTION_ORDERS_FIELD_PRODUCTS_ORDERED = 'productsOrdered'
exports.COLLECTION_ORDERS_FIELD_CREATED_AT = 'createdAt'
exports.COLLECTION_ORDERS_FIELD_MODIFIED_AT = 'modifiedAt'
exports.COLLECTION_ORDERS_FIELD_IS_DELETED = 'isDeleted'

exports.COLLECTION_TESTING = 'Testing'

// ======= HTTP return codes ==========

// INFORMATIVE RESPONSES
exports.HTTP_ANSWER_CODES_100_CONTINUE = 100
exports.HTTP_ANSWER_CODES_101_SWITCHING_PROTOCOL = 101
exports.HTTP_ANSWER_CODES_102_PROCESSING = 102
exports.HTTP_ANSWER_CODES_103_EARLY_HINTS = 103

// SUCCESSFUL RESPONSES
exports.HTTP_ANSWER_CODES_200_OK = 200
exports.HTTP_ANSWER_CODES_201_CREATED = 201
exports.HTTP_ANSWER_CODES_202_ACCEPTED = 202
exports.HTTP_ANSWER_CODES_203_NON_AUTHORITATIVE_INFORMATION = 203
exports.HTTP_ANSWER_CODES_204_NO_CONTENT = 204
exports.HTTP_ANSWER_CODES_205_RESET_CONTENT = 205
exports.HTTP_ANSWER_CODES_206_PARTIAL_CONTENT = 206
exports.HTTP_ANSWER_CODES_207_MULTI_STATUS = 207
exports.HTTP_ANSWER_CODES_208_ALREADY_REPORTED = 208
exports.HTTP_ANSWER_CODES_226_IM_USED = 226

// REDIRECTION RESPONSES
exports.HTTP_ANSWER_CODES_300_MULTIPLE_CHOICE = 300
exports.HTTP_ANSWER_CODES_301_MOVED_PERMANENTLY = 301
exports.HTTP_ANSWER_CODES_302_FOUND = 302
exports.HTTP_ANSWER_CODES_303_SEE_OTHER = 303
exports.HTTP_ANSWER_CODES_304_NOT_MODIFIED = 304
exports.HTTP_ANSWER_CODES_305_USE_PROXY = 305
exports.HTTP_ANSWER_CODES_306_UNUSED = 306
exports.HTTP_ANSWER_CODES_307_TEMPORARY_REDIRECT = 307
exports.HTTP_ANSWER_CODES_308_PERMANENT_REDIRECT = 308

// CLIENT RESPONSES
exports.HTTP_ANSWER_CODES_400_BAD_REQUEST = 400
exports.HTTP_ANSWER_CODES_401_UNAUTHORIZED = 401
exports.HTTP_ANSWER_CODES_402_PAYMENT_REQUIRED = 402
exports.HTTP_ANSWER_CODES_403_FORBIDDEN = 403
exports.HTTP_ANSWER_CODES_404_NOT_FOUND = 404
exports.HTTP_ANSWER_CODES_405_METHOD_NOT_ALLOWED = 405
exports.HTTP_ANSWER_CODES_406_NOT_ACCEPTABLE = 406
exports.HTTP_ANSWER_CODES_407_PROXY_AUTHENTICATION_REQUIRED = 407
exports.HTTP_ANSWER_CODES_408_REQUEST_TIMEOUT = 408
exports.HTTP_ANSWER_CODES_409_CONFLICT = 409
exports.HTTP_ANSWER_CODES_410_GONE = 410
exports.HTTP_ANSWER_CODES_411_LENGTH_REQUIRED = 411
exports.HTTP_ANSWER_CODES_412_PRECONDITION_FAILED = 412
exports.HTTP_ANSWER_CODES_413_PAYLOAD_TOO_LARGE = 413
exports.HTTP_ANSWER_CODES_414_URI_TOO_LONG = 414
exports.HTTP_ANSWER_CODES_415_UNSUPORTED_MEDIA_TYPE = 415
exports.HTTP_ANSWER_CODES_416_RANGE_NOT_SATISFIABLE = 416
exports.HTTP_ANSWER_CODES_417_EXPECTATION_FAILED = 417
exports.HTTP_ANSWER_CODES_418_IM_A_TEAPOT = 418
exports.HTTP_ANSWER_CODES_421_MISDIRECTED_REQUEST = 421
exports.HTTP_ANSWER_CODES_422_UNPROCESSABLE_ENTITY = 422
exports.HTTP_ANSWER_CODES_423_LOCKED = 423
exports.HTTP_ANSWER_CODES_424_FAILED_DEPENDENCY = 424
exports.HTTP_ANSWER_CODES_425_TOO_EARLY = 425
exports.HTTP_ANSWER_CODES_426_UPGRADE_REQUIRED = 426
exports.HTTP_ANSWER_CODES_428_PRECONDITION_REQUIRED = 428
exports.HTTP_ANSWER_CODES_429_TOO_MANY_REQUESTS = 429
exports.HTTP_ANSWER_CODES_431_REQUEST_HEADER_FIELDS_TOO_LARGE = 431
exports.HTTP_ANSWER_CODES_415_UNAVAILABLE_FOR_LEGAL_REASONS = 451

// SERVER ERROR RESPONSES
exports.HTTP_ANSWER_CODES_500_INTERNAL_SERVER_ERROR = 500
exports.HTTP_ANSWER_CODES_501_NOT_IMPLEMENTED = 501
exports.HTTP_ANSWER_CODES_502_BAD_GATEWAY = 502
exports.HTTP_ANSWER_CODES_503_SERVICE_UNAVAILABLE = 503
exports.HTTP_ANSWER_CODES_504_GATEWAY_TIMEOUT = 504
exports.HTTP_ANSWER_CODES_505_HTTP_VERSION_NOT_SUPPORTED = 505
exports.HTTP_ANSWER_CODES_506_VARIANT_ALSO_NEGOTIATES = 506
exports.HTTP_ANSWER_CODES_507_INSUFFICIENT_STORAGE = 507
exports.HTTP_ANSWER_CODES_508_LOOP_DETECTED = 508
exports.HTTP_ANSWER_CODES_510_NOT_EXTENDED = 510
exports.HTTP_ANSWER_CODES_511_NETWORK_AUTHENTICATION_REQUIRED = 511

